### ISSUE TITLE
bug on the "^[^/]*" logic

### ISSUE THREAD

**Issue by NiJoao** [TheBestPessimist/duplicacy-utils#1] opened 2018-02-16 19:37 UTC
From your file:

```
# note: "^[^/]* has the purpose of assuring that there is only 1 "/" before the folder.
# This means that it should match "c:/Recovery/" or "some_sym_link/Recovery/",
#       but not "c:/a/Recovery/" nor "some_sym_link/a/Recovery/"
# In other words, the purpose of that regex is to handle excluding, at least in windows,
#       folders and files which are in root, or in a symlink to root
```

Nice idea.
However, if you want to backup a folder such as c:/ in duplicacy, you either 1) select it as the repo root or 2) make a symlink to C:/ from the root.
Both strategies are widely used in Duplicacy, and depending on it, the file analyzed by the filter rules is:
1) "Recovery/"
2) "some_sym_link/Recovery/"

Therefore, it is simply not possible to know if there should be none or one "/".
You should change the strategy to allow none or one parent directory, such as:
`e:^([^/]+/)?Recovery/`

**Comment by TheBestPessimist** [comment] 2018-02-17 07:21
You are correct with that test. Maybe i should put a note on that

My concern is though: should i really add by default the `"Recovery/"` case?.

What i mean is that there could also be this case:
`F:\DuplicacyRepo` which contains the folders
- `some ultra important files/` (full path: `F:\DuplicacyRepo/some ultra important files/`)
- `Recovery/` (full path: `F:\DuplicacyRepo/Recovery/`).

From that folder structure i really expect the `Recovery` folder to be _for backup_.
With the fix you provide that folder will not be backed up.

I wonder what are other opinions on this as i am not really sure how to continue.

**Comment by TheBestPessimist** [comment] 2018-04-09 16:32
After merging your filters agressive in a0cf57fb598d7e8bc8e7c87d952c1d1651a1c716, I changed the wording so that the user knows the regex only works in <symlink mode>.

Does it look better now?

**Comment by NiJoao** [comment] 2018-10-09 17:46
With the latest versions of duplicacy allowing arbitrary repo paths (`init -repository <path>`), this problem became more important.
The current filters file in this project only supports symlink mode.

It's unsafe to support both ways, as you explained, but maybe we should create a file `filters_root` with the same filters, so users could just rename it if they want to use in "root/path" mode?

I haven't tested the best file_on_root strategy, but it would probably be something like:
`e:(?i)(^/?)Boot/`
instead of
`e:(?i)^[^/]+/Boot/`

**Comment by TheBestPessimist** [comment] 2018-10-10 05:07
I could just create a new filters file which is a duplicate of the existing and use the new exclusion regex. Having to maintain only 2 files isn't that difficult.

**Comment by TheBestPessimist** [comment] 2018-10-23 12:55
I started working on this in #14 if anyone wants to check it out.

**Closed** 2020-04-29 04:52 UTC
Labels: help wanted
